= Анализ задачи

Необходимо разработать приложение, позволяющее создавать и разгадывать канадский кроссворд.

== Функциональные требования

.Режимы работы
* пользовательский (разгадывание);
* режим конструктора (создание).

.Входные данные
* *режим конструктора* - последовательность слов, которые будут составлять кроссворд, подсказки к каждому слову;
* *режим пользователя* - идентификатор желаемого кроссворда.

.Выходные данные
* *режим конструктора* - сгенерированный кроссворд или отчет об ошибке при невозможности его создания;
* *режим пользователя* - сообщение о решении (не решении) кроссворда.

== Нефункциональные требования

* взаимодействие с пользователем - интерфейс коммандной строки (CLI);
* разработка на языке Java;
* используемые библиотеки - только для манипулирования консолью;
* максимальное время работы - не более 1,5 мин. 

== Бизнес-модель

Программа предоставляет два режима работы: пользовательский и конструкторский 
(вследствие чего необходимо реализовать некоторую аутентификацию). + 
В режиме пользователя клиент может выбрать интересующий его кроссворд и разгадывать его. +
В режиме конструктора - создавать кроссворды путем ввода слов и подсказок. +
link:uml/user_case.pu[Диаграмма прецедентов]

== Архитектура приложения

В основе приложения предлагается использовать паттерн MVP.
Это улучшит логическую архитектуру, что позволит легче поддерживать и модифицировать приложение, 
а также позволит абстрагироваться от конкретной реализации пользовательского интерфейса. +
Model предлагается разделить на два компонента: storage и generator, что позволит отделить
алгоритм генерации кроссвордов от способа хранения данных (БД, файлы, ОП). +
Важным пунктом архитектуры классов является взаимодействие блоков View и Presenter.
View имеет ссылку на Presenter, чтобы передавать запросы от пользователя на выполнение
каких-то действий. Presenter имеет ссылку на View, чтобы передавать данные View в ответ на эти запросы
для отображения пользователю. +
link:uml/components.pu[Компоненты программы]

== Реализация

Реализовывать приложение предлагается с помощью следующей логической архитектуры: +
link:uml/classes.pu[Полная диаграмма классов]. +
Для реализации пользовательского интерфейса предлагается использовать
библиотеку link:https://github.com/mabe02/lanterna[lanterna]














