@startuml
    interface "IView"
    interface "IPresenter"
    interface "IGenerator"
    interface "IStorage"
    interface "IGame"

    component [View]
    component [Presenter]
    component [Model]
    component [Storage]
    component [Game]
    component [Generator]
    component [Library]

    IView - View
    IPresenter - Presenter
    IGenerator - Generator
    IStorage - Storage
    IGame - Game
    
    Presenter ..> IView : response   
    Presenter ..> Model : "getting data"
    Model ..> IGame
    Model ..> IGenerator
    Model ..> IStorage
    View ..> Library
    View ..> IPresenter : request

@enduml

